[project]
name = "awsutil"
version = "0.0.1"
description = "AWS CLI utils."
dependencies = [
    "boto3", "click"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.scripts]
awsutil = "awsutil.cli:cli"
